stages:
  - build
  - test

build:
  stage: build
  image: node:latest
  script: 
      - npm install
      - npm run build
      - npm run prod
      
ping pong:
  stage: test
  image: node:latest
  script:
      - npm install
      - npm run build
      - npm run prod
      - curl --location --request GET 'http://localhost:6060/musics/ping' | grep "Pong"

testa ordenacao:
  stage: test
  image: node:latest
  script:
      - npm install
      - npm run build
      - npm run prod
      - 'curl --location --request PUT 'http://localhost:6060/musics' --data-raw '{"name": "Undone thing","review": 5}''
      - 'curl --location --request PUT 'http://localhost:6060/musics' --data-raw '{"name": "Still","review": 3}''
      - 'curl --location --request PUT 'http://localhost:6060/musics' --data-raw '{"name": "One","review": 4}''
      - 'curl --location --request GET 'http://localhost:6060/musics'

cadastra música:
  stage: test
  image: node:latest
  script:
      - npm install
      - npm run build
      - npm run prod
      - 'curl --request POST --header "Content-Type:application/json" --data-raw '{ \"name\": \"Avril Lavigne\" }' http://localhost:6060/musics' | grep "0"'

